version: 0.2

phases:
  pre_build:
    commands:
      - cd frontend
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)

  build:
    commands:
      - echo "Current directory is:"
      - pwd
      - echo "Listing contents of the current directory..."
      - ls -l
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"container_name","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files: frontend/imagedefinitions.json
