version: 0.2

phases:
  pre_build:
    commands:
      - cd frontend

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .

  post_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo Docker images available:
      - docker images
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"container_name","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files: frontend/imagedefinitions.json
