services:
  whiteboard-backend:
    build: ./apps/whiteboard-backend
    ports:
      - "8080:8080"
    volumes:
      - ./apps/whiteboard-backend:/app
    environment:
      RUST_LOG: "info"
    command: ["cargo", "watch", "-x", "run"]

  frontend:
    build: ./apps/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app
      - wasm-build:/app/pkg

  repo-vulgarity-analysis-backend:
    build: ./apps/repo-vulgarity-analysis-backend
    ports:
      - "8081:3000"
    volumes:
      - ./apps/repo-vulgarity-analysis-backend:/app
    depends_on:
      - repo-vulgarity-analysis-database

  database:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  repo-vulgarity-analysis-database:
    image: postgres:17-alpine
    ports:
      - "5433:5433"
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${REPO_VULGARITY_ANALYSIS_DATABASE_USER}"
      POSTGRES_PASSWORD: "${REPO_VULGARITY_ANALYSIS_DATABASE_PASSWORD}"
      POSTGRES_DB: "${REPO_VULGARITY_ANALYSIS_DATABASE_NAME}"
    command: -p 5433
    volumes:
      - repo-vulgarity-analysis-database-data:/var/lib/postgresql/data

  vfx-renderer:
    build:
      context: ./apps/vfx-renderer
      dockerfile: Dockerfile
    volumes:
      - ./apps/vfx-renderer/src:/app/src
      - wasm-build:/app/pkg
    environment:
      - RUST_BACKTRACE=1

volumes:
  postgres_data:
  repo-vulgarity-analysis-database-data:
  wasm-build:
