services:
  backend:
    build: ./apps/backend
    ports:
      - "8080:8080"
    volumes:
      - ./apps/backend:/app
    environment:
      RUST_LOG: "info"
    command: ["cargo", "watch", "-x", "run"]

  frontend:
    build: ./apps/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "app"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
