services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      RUST_LOG: "info"
      DATABASE_URL: "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${DATABASE_NAME}"
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    restart: unless-stopped

  database:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
