version: "3"

tasks:
  dev:
    desc: Start development environment
    cmds:
      - ./bin/start-dev.sh

  build:
    desc: Build image
    cmds:
      - docker-compose -f docker-compose.yml build frontend

  build-envs:
    desc: Generate .env files for all applications
    cmds:
      - ./bin/build-env/build-envs.sh
