version: 0.2
env:
  secrets-manager:
    DOCKERHUB_USERNAME: "portfolio-build-environment:DOCKERHUB_USERNAME"
    DOCKERHUB_PASSWORD: "portfolio-build-environment:DOCKERHUB_PASSWORD"
    AWS_DEFAULT_REGION: "portfolio-build-environment:AWS_DEFAULT_REGION"
    AWS_ACCOUNT_ID: "portfolio-build-environment:AWS_ACCOUNT_ID"
phases:
  install:
    commands:
      - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - ./bin/codeBuild/build.sh analytics-writer
artifacts:
  files: imagedefinitions.json
