name: Deploy to Droplet

on:
  push:
    branches:
      - main # or whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repo to the GitHub Actions runner.
      - name: Check out code
        uses: actions/checkout@v2

      # 2) SSH to the Droplet and run deployment commands.
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          script: |
            cd /root/code/whiteboard
            git pull origin main
            docker-compose down
            docker compose -f compose.prod.yml up --build
